### ISSUE TITLE
Upgrade to current intl (0.16.0)

### ISSUE THREAD

**Issue by noinskit** [cooler-king/quantity#28]
quantity depends on intl "^0.15.0", which is problematic because intl has been on 0.16.* for a while, and now this gets in the way of upgrading to the new stable Flutter 1.12. Could you please upgrade to current intl?

**Comment by cooler-king** [comment]
Thanks for the suggestion.  I will try to push out a new version over the next week or so.

**Comment by cooler-king** [comment]
`intl` dependency updated to `intl: '>=0.15.0 < 1.0.0' in the `dart-sdk-2.3.0` branch... working toward a `1.0.0` release

Until the next release is published you can try using `dependency_overrides` to force use of the newer `intl`.

**Comment by noinskit** [comment]
Any progress? If 1.0.0 is delayed, what about 0.3 in the meantime?

**Comment by cooler-king** [comment]
`quantity 0.3.0` published with relaxed constraint on `intl` version.
