### ISSUE TITLE
Use standard SI units for information

### ISSUE THREAD

**Issue by osechet** [cooler-king/quantity#29]
Unlike what is said in the comments of the Information class, the SI defines the kilobyte as 1000 bytes. The traditional 1024 bytes is called a kibibyte.
Source: https://en.wikipedia.org/wiki/Kibibyte

It would be nice to follow the standard and define the kB, MB, GB... as multiple of 1000 and to add the KiB, GiB... to the library.

**Comment by cooler-king** [comment]
Available in `quantity 1.0.0` published Oct 6.
