### ISSUE TITLE
Support intl 18.0

### ISSUE THREAD

**Issue by smarinier** [cooler-king/quantity#36]
Intl 17-> 18 adds new get/set methods for maximumSignificantDigits and minimumSignificantDigits

As NumberFormatSI from Quantity "implements" NumberFormat, dart compilation breaks on:

Error: The non-abstract class 'NumberFormatSI' is missing implementations for these members:
 - NumberFormat.maximumSignificantDigits
 - NumberFormat.maximumSignificantDigits=
 - NumberFormat.minimumSignificantDigits
 - NumberFormat.minimumSignificantDigits=
 - NumberFormat.minimumSignificantDigitsStrict

(and also its other extended classes : EngineeringFormatSI, ScientificFormatSI)

**Comment by cooler-king** [comment]
Thank you.  I will address this later this week.

**Comment by smarinier** [comment]
This should also fix analysis issue : https://pub.dev/packages/quantity/score

**Comment by cooler-king** [comment]
Community PR merged.
