### ISSUE TITLE
Precise : computation error

### ISSUE THREAD

**Issue by vd3d** [cooler-king/quantity#40]
I got an error in computations when I used the Precise class:

With double:

100.0 * 1007.16 / 10000 = 10.0716

With Precise:

(Precise.num(100.0) * Precise.num(1007.16) / Precise.num(10000)).toDouble() = 0.1716

Is there an error, or it is in the way I use this class ? Any idea ?

Thanks

**Comment by cooler-king** [comment]
Appears to be an error in the library in the Precise divide operator.  Investigating.

**Comment by cooler-king** [comment]
I expect to push an update that resolves the issue by 11/27,

**Comment by cooler-king** [comment]
Version 3.0.1 has been published with fixes to the `Precise` class.  Thank you for opening this issue.
https://pub.dev/packages/quantity/versions/3.0.1
