### ISSUE TITLE
v3.0.2 changes missing

### ISSUE THREAD

**Issue by nebkat** [cooler-king/quantity#42]
It appears that the changes from 3.0.2 have not yet been pushed?

**Comment by cooler-king** [comment]
Thanks.  Updated.

**Comment by nebkat** [comment]
Thank you for the quick response.

I have also identified a bunch of issues with the unit construction functions e.g:

https://github.com/cooler-king/quantity/blob/07ce89dc48013cadca30b6292c256f401b66fe28/lib/src/si/types/mass_density.dart#L54-L62

Which should be `mu.valueSI / vu.valueSI`. I am currently working through these and can provide a PR.

Would there be an appetite for further PRs with non-essential fixes and improvements or is the package somewhat dormant?

**Comment by cooler-king** [comment]
I'm not actively adding new features but I'll fix any problems anyone finds.

**Comment by nebkat** [comment]
No worries - I'll submit a fix for the above first, and I can offer up some PRs after but will probably continue with more aggressive changes in a fork. Thank you for the excellent library!

**Comment by cooler-king** [comment]
Working on these unit fixes now.

**Comment by nebkat** [comment]
@cooler-king FYI I have released a new package inspired by this - https://github.com/nebkat/dart-physical/

**Comment by cooler-king** [comment]
cool!
