### ISSUE TITLE
 WARNING: Problem creating type instance; falling back to MiscQuantity for Dimensions [Length=-2]

### ISSUE THREAD

**Issue by syroezhkin** [cooler-king/quantity#44]
Hello! I'm trying to do a simple physical quantity conversion operation. The result is correct, but it outputs a warning to the console. What does this warning mean and how can I get rid of it?

```dart
import 'package:quantity/quantity_si.dart';

var area = Area(m2: 1);
var force = Force(N: 10);

var pressure = force / area; // => WARNING: Problem creating type instance; falling back to MiscQuantity for Dimensions [Length=-2]
print(pressure); // => 10 Pa
```

**Comment by cooler-king** [comment]
This happens due to an intermediate calculation (inversion of the area to a quantity with dimensions of length:-2).  It can be safely ignored.

The next release will push this logger down to `finest` level.

**Comment by nebkat** [comment]
I would prefer this (https://github.com/cooler-king/quantity/pull/45/commits/047eaad76c424c61d0b8366dc313986dc16ca51a) solution over `finest`, but also perhaps it shouldn't be logged at all? Practically every call to `inverse()` will end up with a misc quantity.

**Comment by cooler-king** [comment]
Ok.  I will look it over, thanks!

**Comment by cooler-king** [comment]
Decided just to remove the logger.
See https://github.com/cooler-king/quantity/pull/46
quantity 4.0.0 published.

**Comment by cooler-king** [comment]
Closing.
